version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "npm"
  directory: "./.github/actions/delete-gcr"
  schedule:
    interval: "daily"
- package-ecosystem: "npm"
  directory: "./tools/ts/minimatchex"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "./tools/rust/sbx"
  schedule:
    interval: "daily"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
