image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
      # https://community.gitpod.io/t/gitpod-docker-issue/3953
      sudo chmod 666 /var/run/docker.sock

vscode:
  extensions:
    - golang.go
    - zxh404.vscode-proto3
