name: "conflict-detector"
description: "Detect github pull request with merge conflicts"
inputs:
  owner:
    description: The name of the owner.
    required: true
  repo:
    description: The name of the repository.
    required: true
  token:
    description: The token used to authenticate with GitHub APIs.
    required: true
  dryrun:
    description: The dry-run feature allows you to inspect before proceeding to post comments.
    required: false
    default: "false"
runs:
  using: "node12"
  main: "dist/index.js"
