name: 'GCR'

on:
  schedule:
  - cron: '30 1 * * 0'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/delete-gcr
        with:
          username: nokamoto
          packagename: sandbox/example
          token: ${{ secrets.PAT }}
          keep: 3
