name: 'GCR'

on:
  schedule:
  - cron: '30 1 * * 0'
  pull_request:
    branches: [ main ]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/delete-gcr
        with:
          username: nokamoto
          packagename: sandbox/example
          token: ${{ secrets.GITHUB_TOKEN }}
          keep: 3
