name: "Go Build"

on:
  workflow_run:
    workflows: ["Go Test"]
    branches: [ main ]
    types:
    - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - uses: buildpacks/github-actions/setup-pack@v4.1.0
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: make go-publish-example TAG=${SHA}
      env:
        SHA: ${{ github.sha }}
    - run: make go-publish-example TAG=latest

