name: Go

on:
  push:
    branches: [ main ]
    paths:
    - 'cmd/**'
    - 'go.mod'
    - '.github/workflows/go.yaml'
  pull_request:
    branches: [ main ]
    paths:
    - 'cmd/**'
    - 'go.mod'
    - '.github/workflows/go.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: go test -v ./...
