name: Go

on:
  push:
    branches: [ main ]
    paths:
    - 'cmd/**'
    - 'internal/**'
    - 'go.mod'
    - '.github/workflows/go.yaml'
  pull_request:
    branches: [ main ]
    paths:
    - 'cmd/**'
    - 'internal/**'
    - 'go.mod'
    - '.github/workflows/go.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: github/codeql-action/init@v1
      with:
        languages: go
    - run: go test -v ./...
    - run: go mod tidy
    - run: go fmt ./...
    - run: git diff --exit-code
    - uses: github/codeql-action/analyze@v1
