name: 'TypeScript actions/delete-gcr'

on:
  push:
    branches: [ main ]
    paths:
    - '.github/actions/delete-gcr/**'
    - '.github/workflows/ts.delete-gcr.yaml'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/actions/delete-gcr/**'
    - '.github/workflows/ts.delete-gcr.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run all
        working-directory: ./.github/actions/delete-gcr
      - run: git diff --exit-code
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/delete-gcr
        with:
          username: nokamoto
          packagename: sandbox/example
          token: ${{ secrets.GITHUB_TOKEN }}
          keep: 3
          dryrun: true
